baseurl = "/"
title = "Luis Sastré"
copyright = "&copy; 2018"
theme = "hugo-theme-dream"
languageCode = "en"
defaultContentLanguage = "en"
# enableRobotsTXT = true

googleAnalytics = "UA-109683885-1"
disqusShortname = "luissas-me"

[params]
  author="LuisSas"
  motto="luissas"
  # description = ""
  # avatar = ""
  email = "luis@makingdevs.com"
  github = "https://github.com/LuisSas"
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""
  siteStartYear = 2017
  aboutHeader = "AboutMe"
  # favicon = "/favicon.ico"
  paginate = 4
